name: home_fi
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_circle_color_picker: ^0.3.0
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  lottie: ^2.6.0
  mqtt_client: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lottie/
    - assets/images/
    - .env # API Key is stored here
